service:
  name: bitwarden-ext-resources
  deletionPolicy:
      prod: Retain
      other: Delete
plugins:
  - serverless-dynamodb-local

custom:
  dynamodb:
    stages:
      - dev

provider:
  name: aws
  region: eu-central-1
  stage: ${opt:stage, 'dev'}
  environment:
    BITWARDEN_TABLE: ${self:service}-${self:provider.stage}-bitwarden
    ATTACHMENTS_BUCKET: ${self:service}-${self:provider.stage}-v1-storage

resources:
  Resources:
    BitwardenTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: ${self:service.deletionPolicy.${self:provider.stage}, self:service.deletionPolicy.other}
      Properties:
        TableName: ${self:provider.environment.BITWARDEN_TABLE}
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
          - AttributeName: email
            AttributeType: S
          - AttributeName: refreshToken
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true
        GlobalSecondaryIndexes:
          - IndexName: InvertedIndex
            KeySchema:
              - AttributeName: sk
                KeyType: HASH
              - AttributeName: pk
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          - IndexName: UserEmailIndex
            KeySchema:
              - AttributeName: email
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          - IndexName: RefreshTokenDeviceIndex
            KeySchema:
              - AttributeName: refreshToken
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
    AttachmentsBucket:
      Type: AWS::S3::Bucket
      DeletionPolicy: ${self:service.deletionPolicy.${self:provider.stage}, self:service.deletionPolicy.other}
      Properties:
        VersioningConfiguration:
          Status: Enabled
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: aws:kms
        BucketName: ${self:provider.environment.ATTACHMENTS_BUCKET}
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders: 
                - Authorization
              AllowedMethods: 
                - GET
              AllowedOrigins:
                - '*'
              MaxAge: 3000

  Outputs:
    BitwardenTableArn:
      Value:
         Fn::GetAtt:
          - BitwardenTable
          - Arn
      Export:
        Name: ${self:provider.stage}-BitwardenTableArn
    AttachmentsBucketArn:
      Value:
         Fn::GetAtt:
          - AttachmentsBucket
          - Arn
      Export:
        Name: ${self:provider.stage}-AttachmentsBucketArn
    AttachmentsBucketName:
      Value:
        Ref: AttachmentsBucket
      Export:
        Name: ${self:provider.stage}-AttachmentsBucket
