service: 
  name: bitwarden-accounts-api

plugins:
  - serverless-webpack
  - serverless-dynamodb-local

custom: ${file(../../../serverless.common.yml):custom}

provider:
  name: aws
  region: eu-central-1
  stage: ${opt:stage, 'dev'}
  runtime: nodejs10.x
  memorySize: 256
  timeout: 10
  environment: ${file(../../../serverless.common.yml):environment}
  iamRoleStatements:
    - ${file(../../../serverless.common.yml):dynamodbRoleStatement}

default_cors: &default_cors
  cors: ${file(../../../serverless.common.yml):cors}

functions:
  # Accounts endpoints
  prelogin:
    handler: prelogin.handler
    events:
      - http:
          method: post
          <<: *default_cors
          path: api/accounts/prelogin
  profile:
    handler: profile.profileHandler
    events:
      - http:
          method: get
          <<: *default_cors
          path: api/accounts/profile
  profile_put:
    handler: profile.putProfileHandler
    events:
      - http:
          method: put
          <<: *default_cors
          path: api/accounts/profile
  keys:
    handler: keys.handler
    events:
      - http:
          method: post
          <<: *default_cors
          path: api/accounts/keys
  register:
    handler: register.handler
    environment:
      DISABLE_USER_REGISTRATION: ${env:DISABLE_USER_REGISTRATION, 'false'}
    events:
      - http:
          method: post
          <<: *default_cors
          path: api/accounts/register
  accounts_revision_date:
    handler: profile.revisionDateHandler
    events:
      - http:
          method: get
          <<: *default_cors
          path: api/accounts/revision-date

resources:
  - Outputs:
      ApiGatewayRestApiId:
        Value:
          Ref: ApiGatewayRestApi
        Export:
          Name: ${self:provider.stage}-ExtApiGatewayRestApiId
    
      ApiGatewayRestApiRootResourceId:
        Value:
           Fn::GetAtt:
            - ApiGatewayRestApi
            - RootResourceId 
        Export:
          Name: ${self:provider.stage}-ExtApiGatewayRestApiRootResourceId
      
      ApiGatewayRestApiResourceApiId:
        Value:
           Ref: ApiGatewayResourceApi
        Export:
          Name: ${self:provider.stage}-ExtApiGatewayRestApiResourceApiId